import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ActionItem {
  item: string;
  assignedTo?: string;
  dueDate?: string;
}

export interface PDFData {
  meetingTitle: string;
  meetingId: string;
  dateStr: string;
  summaryText: string;
  actionItems: ActionItem[];
}

/**
 * Generates a "Meeting Insights" PDF with summary and action items.
 * Returns the PDF as a Base64 string.
 */
export async function generateMeetingPDF(data: PDFData): Promise<string> {
  const { meetingTitle, meetingId, dateStr, summaryText, actionItems } = data;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  // Using a professional blue color #4c51bf (consistent with frontend_2)
  doc.setFillColor(76, 81, 191); 
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Meeting Insights', 20, 20);
  doc.setFontSize(10);
  doc.text(`Meeting Id: ${meetingId}`, 20, 30);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth - 20, 30, { align: 'right' });

  let yPos = 55;

  // Meeting Title
  doc.setTextColor(26, 32, 44);
  doc.setFontSize(20);
  doc.text(meetingTitle, 20, yPos);
  yPos += 10;
  
  // Meeting Date
  doc.setFontSize(10);
  doc.setTextColor(113, 128, 150);
  doc.text(`Meeting Date: ${dateStr}`, 20, yPos);
  yPos += 15;

  // Summary Section
  doc.setTextColor(26, 32, 44);
  doc.setFontSize(16);
  doc.text('Summary', 20, yPos);
  yPos += 8;
  
  doc.setFontSize(11);
  doc.setTextColor(45, 55, 72);
  const splitSummary = doc.splitTextToSize(summaryText, pageWidth - 40);
  doc.text(splitSummary, 20, yPos);
  yPos += (splitSummary.length * 6) + 15;

  // Action Items Section
  if (actionItems && actionItems.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setTextColor(26, 32, 44);
    doc.setFontSize(16);
    doc.text('Action Items', 20, yPos);
    yPos += 5;

    autoTable(doc, {
      startY: yPos,
      head: [['Task', 'Assigned To', 'Due Date']],
      body: actionItems.map(item => [
        item.item, 
        item.assignedTo || '-', 
        item.dueDate || '-'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [76, 81, 191] },
      margin: { left: 20, right: 20 }
    });
  }

  // Footer on all pages
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 174, 192);
    doc.text(
      'Automatically generated by ONIX Meeting Assistant',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  const pdfArrayBuffer = doc.output('arraybuffer');
  return Buffer.from(pdfArrayBuffer).toString('base64');
}
