/**
 * Google Meet Caption Languages
 *
 * Extracted directly from the Google Meet DOM on 2026-02-13.
 * Source of truth: [role="option"] elements in the caption settings panel.
 *
 * DO NOT edit manually — re-run scripts/extract-caption-languages.ts to refresh.
 */

export const GOOGLE_MEET_CAPTION_LANGUAGES = [
    "Afrikaans (South Africa)",
    "Albanian (Albania)",
    "Amharic (Ethiopia)",
    "Arabic (Egypt)",
    "Arabic (Levant)",
    "Arabic (Maghrebi)",
    "Arabic (Peninsular Gulf)",
    "Arabic (United Arab Emirates)",
    "Armenian (Armenia)",
    "Azerbaijani (Azerbaijan)",
    "Basque (Spain)",
    "Bengali (Bangladesh)",
    "Bulgarian (Bulgaria)",
    "Burmese (Myanmar)",
    "Catalan (Spain)",
    "Chinese, Cantonese (Traditional)",
    "Chinese, Mandarin (Simplified)",
    "Chinese, Mandarin (Traditional)",
    "Czech (Czech Republic)",
    "Dutch",
    "English",
    "English (Australia)",
    "English (India)",
    "English (Philippines)",
    "English (UK)",
    "Estonian (Estonia)",
    "Filipino (Philippines)",
    "Finnish (Finland)",
    "French",
    "French (Canada)",
    "Galician (Spain)",
    "Georgian (Georgia)",
    "German",
    "Greek (Greece)",
    "Gujarati (India)",
    "Hebrew (Israel)",
    "Hindi",
    "Hungarian (Hungary)",
    "Icelandic (Iceland)",
    "Indonesian (Indonesia)",
    "Italian",
    "Japanese",
    "Javanese (Indonesia)",
    "Kannada (India)",
    "Kazakh (Kazakhstan)",
    "Khmer (Cambodia)",
    "Kinyarwanda (Rwanda)",
    "Korean",
    "Lao (Laos)",
    "Latvian (Latvia)",
    "Lithuanian (Lithuania)",
    "Macedonian (North Macedonia)",
    "Malay (Malaysia)",
    "Malayalam (India)",
    "Marathi (India)",
    "Mongolian (Mongolia)",
    "Nepali (Nepal)",
    "Northern Sotho (South Africa)",
    "Norwegian (Norway)",
    "Persian (Iran)",
    "Polish (Poland)",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Romanian (Romania)",
    "Russian",
    "Serbian (Serbia)",
    "Sesotho (South Africa)",
    "Sinhala (Sri Lanka)",
    "Slovak (Slovakia)",
    "Slovenian (Slovenia)",
    "Spanish (Mexico)",
    "Spanish (Spain)",
    "Sundanese (Indonesia)",
    "Swahili",
    "Swati (South Africa)",
    "Swedish (Sweden)",
    "Tamil (India)",
    "Telugu (India)",
    "Thai (Thailand)",
    "Tshivenda (South Africa)",
    "Tswana (South Africa)",
    "Turkish (Turkey)",
    "Ukrainian (Ukraine)",
    "Urdu (Pakistan)",
    "Uzbek (Uzbekistan)",
    "Vietnamese (Vietnam)",
    "Xhosa (South Africa)",
    "Xitsonga (South Africa)",
    "Zulu (South Africa)",
] as const;

export type CaptionLanguage = (typeof GOOGLE_MEET_CAPTION_LANGUAGES)[number];

export const DEFAULT_CAPTION_LANGUAGE: CaptionLanguage = "English";
