/**
 * Email Service using SendGrid
 * Handles sending meeting summary emails to participants
 */

import sgMail from '@sendgrid/mail';

// Initialize SendGrid
if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export interface EmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  from?: string;
}

/**
 * Send email using SendGrid
 */
export async function sendEmail(options: EmailOptions): Promise<void> {
  if (!process.env.SENDGRID_API_KEY) {
    throw new Error('SENDGRID_API_KEY is not configured');
  }

  const fromEmail = options.from || process.env.SENDGRID_FROM_EMAIL || 'noreply@onix.ai';

  const msg = {
    to: options.to,
    from: fromEmail,
    subject: options.subject,
    html: options.html,
  };

  try {
    await sgMail.send(msg);
    console.log(`✅ Email sent successfully to ${Array.isArray(options.to) ? options.to.join(', ') : options.to}`);
  } catch (error: any) {
    console.error('❌ Error sending email:', error);
    if (error.response) {
      console.error('SendGrid error details:', error.response.body);
    }
    throw error;
  }
}

/**
 * Generate HTML email template for meeting summary
 */
export function generateSummaryEmailHTML(
  meetingTitle: string,
  summaryText: string,
  meetingDate: string,
  meetingUrl?: string,
  actionItems?: string[]
): string {
  const actionItemsHTML = actionItems && actionItems.length > 0
    ? `
      <div style="margin-top: 24px;">
        <h3 style="color: #1f2937; font-size: 18px; margin-bottom: 12px;">Action Items:</h3>
        <ul style="list-style-type: disc; padding-left: 24px; color: #374151;">
          ${actionItems.map(item => `<li style="margin-bottom: 8px;">${item}</li>`).join('')}
        </ul>
      </div>
    `
    : '';

  const meetingLinkHTML = meetingUrl
    ? `<p style="margin-top: 16px;"><a href="${meetingUrl}" style="color: #2563eb; text-decoration: none;">View Meeting Details →</a></p>`
    : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #1f2937; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9fafb;">
      <div style="background-color: #ffffff; border-radius: 8px; padding: 32px; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);">
        <div style="margin-bottom: 24px;">
          <h1 style="color: #111827; font-size: 24px; margin: 0 0 8px 0;">Meeting Summary</h1>
          <p style="color: #6b7280; font-size: 14px; margin: 0;">${meetingDate}</p>
        </div>
        
        <div style="background-color: #f3f4f6; border-left: 4px solid #2563eb; padding: 16px; margin-bottom: 24px; border-radius: 4px;">
          <h2 style="color: #111827; font-size: 20px; margin: 0 0 12px 0;">${meetingTitle}</h2>
        </div>

        <div style="margin-top: 24px;">
          <h3 style="color: #1f2937; font-size: 18px; margin-bottom: 12px;">Summary:</h3>
          <div style="color: #374151; white-space: pre-wrap; background-color: #f9fafb; padding: 16px; border-radius: 4px; line-height: 1.8;">
            ${summaryText}
          </div>
        </div>

        ${actionItemsHTML}

        ${meetingLinkHTML}

        <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          <p style="margin: 0;">This summary was automatically generated by ONIX Meeting Assistant.</p>
        </div>
      </div>
    </body>
    </html>
  `;
}

/**
 * Send meeting summary email to participants
 */
export async function sendMeetingSummaryEmail(
  participantEmails: string[],
  meetingTitle: string,
  summaryText: string,
  meetingDate: string,
  meetingUrl?: string,
  actionItems?: string[]
): Promise<void> {
  if (participantEmails.length === 0) {
    console.log('⚠️ No participant emails provided, skipping email send');
    return;
  }

  const html = generateSummaryEmailHTML(meetingTitle, summaryText, meetingDate, meetingUrl, actionItems);
  const subject = `Meeting Summary: ${meetingTitle}`;

  try {
    await sendEmail({
      to: participantEmails,
      subject,
      html,
    });
    console.log(`✅ Meeting summary emails sent to ${participantEmails.length} participants`);
  } catch (error) {
    console.error('❌ Failed to send meeting summary emails:', error);
    throw error;
  }
}


