// Next.js API route for starting meeting bot
import { NextRequest, NextResponse } from 'next/server';
import { getAuth } from 'firebase-admin/auth';
import admin from 'firebase-admin';

// Initialize Firebase Admin if not already initialized
if (!admin.apps.length) {
  const serviceAccount = require('../../../../backend/firebase-service-account.json');
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  });
}

// Meeting Bot Integration

export async function POST(request: NextRequest) {
  try {
    // Get Firebase token from headers
    const authHeader = request.headers.get('authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'No token provided' }, { status: 401 });
    }

    const token = authHeader.split('Bearer ')[1];
    
    // Verify Firebase token
    const decodedToken = await getAuth().verifyIdToken(token);
    const userId = decodedToken.uid;

    // Get meeting URL and title from request body
    const { meetingUrl, meetingTitle } = await request.json();
    if (!meetingUrl) {
      return NextResponse.json({ error: 'Meeting URL required' }, { status: 400 });
    }

    // Forward to backend to start container (backend will create the job if needed)
    const botResponse = await fetch('http://localhost:3001/submit-link', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        url: meetingUrl,
        userId,
        meetingTitle: meetingTitle || 'Untitled Meeting'
      })
    });
    
    if (!botResponse.ok) {
      throw new Error('Bot failed to start');
    }

    const data = await botResponse.json().catch(() => ({}));
    const jobId = data.jobId;
    const meetingId = data.meetingId;

    // Store meeting info in Firestore for later calendar matching
    // The meetingId will be generated by the bot later, so we'll update it then
    const db = admin.firestore();
    if (jobId) {
      // Store with jobId as temporary identifier
      // The bot will generate meetingId later, and we'll update this document
      await db.collection('meetings').doc(jobId).set({
        jobId,
        userId,
        meetingUrl,
        meetingTitle: meetingTitle || 'Untitled Meeting',
        status: 'started',
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      }, { merge: true });
    }

    // If meetingId is already available, try to match calendar event
    if (meetingId) {
      // Update Firestore with meetingId
      if (jobId) {
        await db.collection('meetings').doc(jobId).update({
          meetingId,
        });
      }
      
      // Try to match calendar event (non-blocking)
      try {
        const matchResponse = await fetch(`${request.nextUrl.origin}/api/meetings/match-calendar-event`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            meetingUrl,
            meetingId,
          }),
        });

        if (matchResponse.ok) {
          const matchData = await matchResponse.json();
          console.log('✅ Calendar event matched:', matchData);
        } else {
          console.log('⚠️ Calendar event matching failed (non-critical)');
        }
      } catch (matchError) {
        console.log('⚠️ Calendar event matching error (non-critical):', matchError);
      }
    }

    return NextResponse.json({ success: true, ...data });

  } catch (error) {
    console.error('Error starting meeting bot:', error);
    return NextResponse.json({ error: 'Failed to start meeting bot' }, { status: 500 });
  }
}
